version: '3.7'
services:
  app:
    image: rlagutinhub/docker.weblogic-adminserver-app:12.2.1.2-generic_custom
    networks:
       - proxy
    volumes:
      - /data/logs:/u01/oracle/logs:rw
      - /data/tmp:/u01/oracle/tmp:rw
    configs:
      - source: hello_domain_settings.properties.2019-09-05
        target: /u01/oracle/properties/domain_settings.properties
    stop_grace_period: 2m
    deploy:
      # mode: global
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        # order: stop-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        # https://docs.traefik.io/configuration/backends/docker/#on-containers
        - "traefik.enable=true"
        - "traefik.port=7001"
        # - "traefik.weight=10"
        - "traefik.frontend.rule=Host:hello.example.com,hello.test.example.com"
        # - "traefik.frontend.rule=Host:hello.example.com,hello.test.example.com;AddPrefix:/hello;"
        - "traefik.frontend.entryPoints=http"
        # - "traefik.frontend.entryPoints=http,https"
        # - "traefik.frontend.headers.SSLRedirect=true"
        # - "traefik.frontend.auth.basic.users=root:$$apr1$$mLRjS/wr$$QqrALWNDgW9alDmnb9DeK1"
        # - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.method=wrr"
      placement:
        constraints:
          # - node.role == manager
          # - node.role == worker
          - node.labels.hello == true
networks:
  proxy:
    external: true
configs:
  hello_domain_settings.properties.2019-09-05:
    external: true
